server:
  port: 9090

spring:
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/springboot?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: root
  batch:
    initialize-schema: always
#    job:
#      enabled: false
#    job:
#      names: parentJob
#    schema: org/springframework/batch/core/schema-mysql.sql