server:
  port: 8080

spring:
  application:
    name: springboot-redis
  redis:
    # Redis数据库索引（默认为0）
    database: 0
    host: localhost
    port: 6379
    password: xxxxx
    # 连接超时时间（毫秒）
    timeout: 1000
    # 在 Spring Boot 2.x 以后底层不再使用 Jedis，而是换成了 Lettuce。
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: -1
        min-idle: 0
#    jedis:
#      pool:
#        # 连接池最大连接数（使用负值表示没有限制）
#        max-active: 8
#        #连接池最大阻塞等待时间（使用负值表示没有限制）
#        max-wait: -1
#        # 连接池中的最大空闲连接
#        max-idle: 8
#        # 连接池中的最小空闲连接
#        min-idle: 0



