server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springboot?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: root


#多数据源配置
#spring:
#  datasource:
#    dynamic:
#      primary: master #设置默认的数据源或者数据源组,默认值即为master
#      datasource:
#        master:
#          username: root
#          password: root
#          driver-class-name: com.mysql.cj.jdbc.Driver
#          url: jdbc:mysql://localhost:3306/springboot?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
#        slave:
#          username: root
#          password: root
#          driver-class-name: com.mysql.cj.jdbc.Driver
#          url: jdbc:mysql://localhost:3306/springboot-slave?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai

#  配置xml扫描路径
mybatis-plus:
  mapper-locations: classpath*:/mapper/*.xml